filebeat.inputs:
  - type: container
    paths:
      - "C:/Users/darek/Documents/Repos/AI-agent-exercise/app.log"
    json.keys_under_root: true
    json.add_error_key: true
    processors:
      - add_docker_metadata: ~
      - decode_json_fields:
          fields: ["log"]
          overwrite_keys: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"